export const Actions = {
  'send-message': {},
  'send-reaction': {},
  'call': {},
  'make-conversation': {},
  'make-invite': {},
  'send-message-to-group': {},
  'send-reaction-to-group': {},
  'call-group': {},
  'create-project': {},
  'delete-project': {},
  'add-desk-to-project': {},
  'remove-desk-from-project': {},
  'publish-contract': {},
  'publish-gall-app': {},
  'create-file': {},
  'create-file-from-template': {},
  'edit-file': {},
  'delete-file': {},
  'create-table': {},
  'start-game': {},
  'create-link-to-table': {},
}